# Generated by Django 5.2 on 2025-05-02 16:22

import django.core.validators
import django.db.models.deletion
import django_fsm
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this object.', unique=True, verbose_name='UID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Object created at.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Object updated at.', verbose_name='Updated At')),
                ('status', django_fsm.FSMField(choices=[('placed', 'Placed'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='placed', help_text='Status of the order', max_length=24, verbose_name='Order Status')),
                ('accepted_at', models.DateTimeField(blank=True, help_text='Date and time the order was accepted.', null=True, verbose_name='Accepted At')),
                ('rejected_at', models.DateTimeField(blank=True, help_text='Date and time the order was rejected.', null=True, verbose_name='Rejected At')),
                ('customer_id', models.CharField(help_text='Unique identifier for the customer who placed the order.', max_length=255, verbose_name='Customer ID')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this object.', unique=True, verbose_name='UID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Object created at.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Object updated at.', verbose_name='Updated At')),
                ('item_id', models.CharField(help_text='Unique identifier of the item.', max_length=255, verbose_name='Item ID')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of items ordered.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('order', models.ForeignKey(help_text='Order linked to object.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['created_at'],
                'constraints': [models.UniqueConstraint(fields=('order', 'item_id'), name='order__orderitem__unique_fields')],
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this object.', unique=True, verbose_name='UID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Object created at.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Object updated at.', verbose_name='Updated At')),
                ('payment_info_id', models.CharField(help_text='Unique identifier for the order payment.', max_length=255, verbose_name='Payment Info ID')),
                ('order', models.ForeignKey(help_text='Order linked to object.', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='order.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order Payment',
                'verbose_name_plural': 'Order Payments',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('order', 'payment_info_id'), name='order__orderpayment__unique_fields')],
            },
        ),
    ]
